"""empty message

Revision ID: 06884d161404
Revises: 3597452e9a8f
Create Date: 2024-07-20 21:24:09.354625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06884d161404'
down_revision = '3597452e9a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_phone', sa.String(length=100), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_phone', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('user_phone')

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('user_phone')

    # ### end Alembic commands ###
